### PR TITLE
Fix directive invalid

### PR DESCRIPTION
**Pull request by pilou-**
Oups, there was a typo in the previous PR (#1), this PR fixes:
- fix a typo in `nginx.conf` and increase again `client_max_body_size`
- fix a typo in doc (in documentation)
- improve doc related to data persistence

### CODE REVIEW

**Comment by g-LuL** [comment]
Hi,
Another issue  I guess : postgresql failed at start.
I found this in supervisord.log : 

> 2017-11-14 17:31:49,354 INFO gave up: postgresql entered FATAL state, too many start retries too quickly

**Comment by g-LuL** [comment]
Oups, forger about my last coment : I guess my postgresql schema should be updated...

**Comment by g-LuL** [comment]
So i tried to update the postgresql database schema following the update part in zou doc but postgresql is stopped in the image so i cannot update the db. I tried to start postgresql manually without success. Maybe you could help me @pilou- ?

**Comment by pilou-** [comment]
The owner should be changed in the container.

Could you try with https://github.com/pilou-/docker-cgwire/tree/fix_perms ?

A better way would to use docker volume instead of a bind mount.

**Pull request merged**
